src/Entity/Activity.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Export\Annotation as Exporter;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Swagger\Annotations as SWG;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="kimai2_activities",
 *      indexes={
 *          @ORM\Index(columns={"visible","project_id"}),
 *          @ORM\Index(columns={"visible","project_id","name"}),
 *          @ORM\Index(columns={"visible","name"})
 *      }
 * )
 * @ORM\Entity(repositoryClass="App\Repository\ActivityRepository")
 *
 * @Serializer\ExclusionPolicy("all")
 * @Serializer\VirtualProperty(
 *      "ProjectName",
 *      exp="object.getProject() === null ? null : object.getProject().getName()",
 *      options={
 *          @Serializer\SerializedName("parentTitle"),
 *          @Serializer\Type(name="string"),
 *          @Serializer\Groups({"Activity"})
 *      }
 * )
 * @Serializer\VirtualProperty(
 *      "ProjectAsId",
 *      exp="object.getProject() === null ? null : object.getProject().getId()",
 *      options={
 *          @Serializer\SerializedName("project"),
 *          @Serializer\Type(name="integer"),
 *          @Serializer\Groups({"Activity", "Team", "Not_Expanded"})
 *      }
 * )
 *
 * @Exporter\Order({"id", "name", "project", "budget", "timeBudget", "color", "visible", "comment"})
 * @Exporter\Expose("project", label="label.project", exp="object.getProject() === null ? null : object.getProject().getName()")
 * @ Exporter\Expose("teams", label="label.team", exp="object.getTeams().toArray()", type="array")
 */
class Activity implements EntityWithMetaFields
{
    /**
     * Internal ID
     *
     * @var int|null
     *
     * @Serializer\Expose()
     * @Serializer\Groups({"Default"})
     *
     * @Exporter\Expose(label="label.id", type="integer")
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
    /**
     * @var Project|null
     *
     * @Serializer\Expose()
     * @Serializer\Groups({"Subresource", "Expanded"})
     * @SWG\Property(ref="#/definitions/Project")
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Project")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $project;
    /**
     * Name of this activity
     *
     * @var string
     *
     * @Serializer\Expose()
     * @Serializer\Groups({"Default"})
     *
     * @Exporter\Expose(label="label.name")
     *
     * @ORM\Column(name="name", type="string", length=150, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(min=2, max=150, allowEmptyString=false)
     */
    private $name;
    /**
     * Description of this activity
     *
     * @var string
     *
     * @Serializer\Expose()
     * @Serializer\Groups({"Activity_Entity"})
     *
     * @Exporter\Expose(label="label.comment")
     *
     * @ORM\Column(name="comment", type="text", nullable=true)
     */
    private $comment;
    /**
     * Whether this activity is visible and can be used for timesheets
     *
     * @var bool
     *
     * @Serializer\Expose()
     * @Serializer\Groups({"Default"})
     *
     * @Exporter\Expose(label="label.visible", type="boolean")
     *
     * @ORM\Column(name="visible", type="boolean", nullable=false, options={"default": true})
     * @Assert\NotNull()
     */
    private $visible = true;

    // keep the traits here, for placing the column at the "correct" position
    use ColorTrait;

    /**
     * The total monetary budget, will be zero if unconfigured.
     *
     * @var float
     *
     * @Serializer\Expose()
     * @Serializer\Groups({"Activity_Entity"})
     *
     * @ Exporter\Expose(label="label.budget")
     *
     * @ORM\Column(name="budget", type="float", nullable=false)
     * @Assert\NotNull()
     */
    private $budget = 0.00;
    /**
     * The time budget in seconds, will be be zero if unconfigured.
     *
     * @var int
     *
     * @Serializer\Expose()
     * @Serializer\Groups({"Activity_Entity"})
     *
     * @ Exporter\Expose(label="label.timeBudget", type="duration")
     *
     * @ORM\Column(name="time_budget", type="integer", nullable=false)
     * @Assert\NotNull()
     */
    private $timeBudget = 0;
    /**
     * Meta fields
     *
     * All visible meta (custom) fields registered with this activity
     *
     * @var ActivityMeta[]|Collection
     *
     * @Serializer\Expose()
     * @Serializer\Groups({"Activity"})
     * @Serializer\Type(name="array<App\Entity\ActivityMeta>")
     * @Serializer\SerializedName("metaFields")
     * @Serializer\Accessor(getter="getVisibleMetaFields")
     *
     * @ORM\OneToMany(targetEntity="App\Entity\ActivityMeta", mappedBy="activity", cascade={"persist"})
     */
    private $meta;
    /**
     * Teams
     *
     * If no team is assigned, everyone can access the activity
     *
     * @var Team[]|ArrayCollection
     *
     * @Serializer\Expose()
     * @Serializer\Groups({"Activity"})
     * @SWG\Property(type="array", @SWG\Items(ref="#/definitions/Team"))
     *
     * @ORM\ManyToMany(targetEntity="Team", cascade={"persist"}, inversedBy="activities")
     * @ORM\JoinTable(
     *  name="kimai2_activities_teams",
     *  joinColumns={
     *      @ORM\JoinColumn(name="activity_id", referencedColumnName="id", onDelete="CASCADE")
     *  },
     *  inverseJoinColumns={
     *      @ORM\JoinColumn(name="team_id", referencedColumnName="id", onDelete="CASCADE")
     *  }
     * )
     */
    private $teams;

    public function __construct()
    {
        $this->meta = new ArrayCollection();
        $this->teams = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): Activity
    {
        $this->project = $project;

        return $this;
    }

    public function setName(string $name): Activity
    {
        $this->name = $name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setComment(?string $comment): Activity
    {
        $this->comment = $comment;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setVisible(bool $visible): Activity
    {
        $this->visible = $visible;

        return $this;
    }

    public function isGlobal(): bool
    {
        return $this->project === null;
    }

    public function isVisible(): bool
    {
        return $this->visible;
    }

    public function setBudget(float $budget): Activity
    {
        $this->budget = $budget;

        return $this;
    }

    public function getBudget(): float
    {
        return $this->budget;
    }

    public function setTimeBudget(int $seconds): Activity
    {
        $this->timeBudget = $seconds;

        return $this;
    }

    public function getTimeBudget(): int
    {
        return $this->timeBudget;
    }

    /**
     * @return Collection|MetaTableTypeInterface[]
     */
    public function getMetaFields(): Collection
    {
        return $this->meta;
    }

    /**
     * @return MetaTableTypeInterface[]
     */
    public function getVisibleMetaFields(): array
    {
        $all = [];
        foreach ($this->meta as $meta) {
            if ($meta->isVisible()) {
                $all[] = $meta;
            }
        }

        return $all;
    }

    public function getMetaField(string $name): ?MetaTableTypeInterface
    {
        foreach ($this->meta as $field) {
            if (strtolower($field->getName()) === strtolower($name)) {
                return $field;
            }
        }

        return null;
    }

    public function setMetaField(MetaTableTypeInterface $meta): EntityWithMetaFields
    {
        if (null === ($current = $this->getMetaField($meta->getName()))) {
            $meta->setEntity($this);
            $this->meta->add($meta);

            return $this;
        }

        $current->merge($meta);

        return $this;
    }

    public function addTeam(Team $team)
    {
        if ($this->teams->contains($team)) {
            return;
        }

        $this->teams->add($team);
        $team->addActivity($this);
    }

    public function removeTeam(Team $team)
    {
        if (!$this->teams->contains($team)) {
            return;
        }
        $this->teams->removeElement($team);
        $team->removeActivity($this);
    }

    /**
     * @return Collection<Team>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getName();
    }

    public function __clone()
    {
        if ($this->id) {
            $this->id = null;
            $this->meta = new ArrayCollection();
        }
    }
}

src/Form/Type/CustomerType.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form\Type;

use App\Entity\Customer;
use App\Repository\CustomerRepository;
use App\Repository\Query\CustomerFormTypeQuery;
use App\Repository\Query\ProjectQuery;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Custom form field type to select a customer.
 */
class CustomerType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // documentation is for NelmioApiDocBundle
            'documentation' => [
                'type' => 'integer',
                'description' => 'Customer ID',
            ],
            'label' => 'label.customer',
            'class' => Customer::class,
            'choice_label' => 'name',
            'query_builder_for_user' => true,
            'project_enabled' => false,
            'project_select' => 'project',
            'start_date_param' => '%begin%',
            'end_date_param' => '%end%',
            'ignore_date' => false,
            'project_visibility' => ProjectQuery::SHOW_VISIBLE,
        ]);

        $resolver->setDefault('query_builder', function (Options $options) {
            return function (CustomerRepository $repo) use ($options) {
                $query = new CustomerFormTypeQuery();
                if (true === $options['query_builder_for_user']) {
                    $query->setUser($options['user']);
                }

                return $repo->getQueryBuilderForFormType($query);
            };
        });

        $resolver->setDefault('api_data', function (Options $options) {
            if (false !== $options['project_enabled']) {
                $name = \is_string($options['project_enabled']) ? $options['project_enabled'] : 'customer';
                $routeParams = [$name => '%' . $name . '%', 'visible' => $options['project_visibility']];
                $emptyRouteParams = ['visible' => $options['project_visibility']];

                if (!$options['ignore_date']) {
                    if (!empty($options['start_date_param'])) {
                        $routeParams['start'] = $options['start_date_param'];
                        $emptyRouteParams['start'] = $options['start_date_param'];
                    }

                    if (!empty($options['end_date_param'])) {
                        $routeParams['end'] = $options['end_date_param'];
                        $emptyRouteParams['end'] = $options['end_date_param'];
                    }
                } else {
                    $routeParams['ignoreDates'] = 1;
                    $emptyRouteParams['ignoreDates'] = 1;
                }

                return [
                    'select' => $options['project_select'],
                    'route' => 'get_projects',
                    'route_params' => $routeParams,
                    'empty_route_params' => $emptyRouteParams,
                ];
            }

            return [];
        });
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return EntityType::class;
    }
}

templates/customer/actions.html.twig
{% macro customers(view) %}
    {% import "macros/widgets.html.twig" as widgets %}

    {% set actions = {'search': {'class': 'search-toggle visible-xs-inline'}, 'visibility': '#modal_customer_admin'} %}

    {% set actions = actions|merge({'download': {'url': path('customer_export'), 'class': 'toolbar-action'}}) %}

    {% if is_granted('create_customer') %}
        {% set actions = actions|merge({'create': path('admin_customer_create')}) %}
    {% endif %}

    {% set actions = actions|merge({'help': {'url': 'customer.html'|docu_link, 'target': '_blank'}}) %}

    {% set event = trigger('actions.customers', {'actions': actions, 'view': view}) %}
    {{ widgets.page_actions(event.payload.actions) }}
{% endmacro %}

{% macro customer(customer, view, options) %}
    {% import "macros/widgets.html.twig" as widgets %}
    {% set actions = {} %}

    {% if customer.id is not empty %}
        {% if view != 'details' and is_granted('view', customer) %}
            {% set actions = actions|merge({'details': path('customer_details', {'id': customer.id})}) %}
        {% endif %}
        {% if is_granted('edit', customer) %}
            {% set class = '' %}
            {% if view != 'edit' %}
                {% set class = 'modal-ajax-form' %}
            {% endif %}
            {% set actions = actions|merge({'edit': {'url': path('admin_customer_edit', {'id': customer.id}), 'class': class}}) %}
        {% endif %}
        {% if is_granted('permissions', customer) %}
            {% set class = '' %}
            {% if view != 'permissions' %}
                {% set class = 'modal-ajax-form' %}
            {% endif %}
            {% set actions = actions|merge({'permissions': {'url': path('admin_customer_permissions', {'id': customer.id}), 'class': class}}) %}
        {% endif %}
        {% if actions|length > 0 %}
            {% set actions = actions|merge({'divider': null}) %}
        {% endif %}
        {% if is_granted('view_project') or is_granted('view_teamlead_project') or is_granted('view_team_project') %}
            {% set actions = actions|merge({'project': path('admin_project', {'customers[]': customer.id})}) %}
        {% endif %}
        {% if is_granted('view_activity') %}
            {% set actions = actions|merge({'activity': path('admin_activity', {'customers[]': customer.id})}) %}
        {% endif %}
        {% if is_granted('view_other_timesheet') %}
            {% set actions = actions|merge({'timesheet': path('admin_timesheet', {'customers[]': customer.id})}) %}
        {% endif %}
        {% if customer.visible and is_granted('create_project') %}
            {% set actions = actions|merge({'create-project': {'url': path('admin_project_create_with_customer', {'customer': customer.id}), 'class': 'modal-ajax-form'}}) %}
        {% endif %}
        {% if view == 'index' and is_granted('delete', customer) %}
            {% set actions = actions|merge({'trash': {'url': path('admin_customer_delete', {'id': customer.id}), 'class': 'modal-ajax-form'}}) %}
        {% endif %}
    {% endif %}

    {% if view != 'index' and view != 'custom' %}
        {% set actions = actions|merge({'back': options.back|default(path('admin_customer'))}) %}
    {% endif %}

    {% set event = trigger('actions.customer', {'actions': actions, 'view': view, 'customer': customer}) %}
    {% if view == 'index' or view == 'custom' %}
        {{ widgets.table_actions(event.payload.actions) }}
    {% else %}
        {{ widgets.entity_actions(event.payload.actions) }}
    {% endif %}
{% endmacro %}

templates/customer/delete.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}
{% import "customer/actions.html.twig" as actions %}

{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}
{% block page_actions %}{{ actions.customer(customer, 'delete') }}{% endblock %}

{% block main %}

    {% set inUse = (stats.recordAmount > 0) %}

    {% set params = {
        '%activity%': '<strong>' ~ stats.activityAmount ~ '</strong>',
        '%project%': '<strong>' ~ stats.projectAmount ~ '</strong>',
        '%customer%': '<strong>' ~ customer.name ~ '</strong>',
        '%records%': '<strong>' ~ stats.recordAmount ~ '</strong>',
        '%duration%': '<strong>' ~ stats.recordDuration|duration ~ '</strong>'
    } %}

    {% set message = '<p>' ~ ("admin_customer.short_stats"|trans(params)|raw) ~ '</p><p>' ~ ("admin_entity.delete_confirm"|trans|raw) ~ '</p>' %}

    {{ include(app.request.xmlHttpRequest ? 'default/_form_delete_modal.html.twig' : 'default/_form_delete.html.twig', {
        'message': message|raw,
        'form': form,
        'used': inUse,
        'back': path('admin_customer')
    }) }}

{% endblock %}

templates/customer/details.html.twig
{% extends 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}
{% import "customer/actions.html.twig" as actions %}

{% block page_actions %}{{ actions.customer(customer, 'details') }}{% endblock %}
{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}

{% block main %}
    {% set can_edit = is_granted('edit', customer) %}

    {% embed '@AdminLTE/Widgets/box-widget.html.twig' %}
        {% import "macros/widgets.html.twig" as widgets %}
        {% block box_attributes %}id="customer_details_box"{% endblock %}
        {% block box_title %}
            {{ widgets.label_customer(customer) }}
            {% if customer.company is not empty %} &ndash; {{ customer.company }}{% endif %}
        {% endblock %}
        {% block box_tools %}
            {% if can_edit %}
                <a class="modal-ajax-form open-edit btn btn-default btn-sm" data-href="{{ path('admin_customer_edit', {'id': customer.id}) }}" data-toggle="tooltip" data-placement="top" title="{{ 'action.edit'|trans }}"><i class="{{ 'edit'|icon }}"></i></a>
            {% endif %}
        {% endblock %}
        {% block box_body_class %}no-padding{% endblock %}
        {% block box_body %}
            {% if customer.comment is not empty %}
                <div class="comment">
                    {{ customer.comment|comment2html(true) }}
                </div>
            {% endif %}
            <table class="table table-hover dataTable">
                {% if not customer.visible %}
                    <tr>
                        <th>{{ 'label.visible'|trans }}</th>
                        <td>
                            {{ widgets.label_boolean(customer.visible) }}
                        </td>
                    </tr>
                {% endif %}
                {% if customer.address is not empty %}
                    <tr>
                        <th>{{ 'label.address'|trans }}</th>
                        <td>
                            {{ customer.address|nl2br }}

                            {% if customer.country is not empty %}
                                <br>
                                {{ customer.country|country }}
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
                {% if customer.contact is not empty %}
                    <tr>
                        <th>{{ 'label.contact'|trans }}</th>
                        <td>{{ customer.contact }}</td>
                    </tr>
                {% endif %}
                {% if customer.phone is not empty %}
                    <tr>
                        <th>{{ 'label.phone'|trans }}</th>
                        <td><a href="tel:{{ customer.phone }}">{{ customer.phone }}</a></td>
                    </tr>
                {% endif %}
                {% if customer.mobile is not empty %}
                    <tr>
                        <th>{{ 'label.mobile'|trans }}</th>
                        <td><a href="tel:{{ customer.mobile }}">{{ customer.mobile }}</a></td>
                    </tr>
                {% endif %}
                {% if customer.email is not empty %}
                    <tr>
                        <th>{{ 'label.email'|trans }}</th>
                        <td><a href="mailto:{{ customer.email }}">{{ customer.email }}</a></td>
                    </tr>
                {% endif %}
                {% if customer.homepage is not empty %}
                    <tr>
                        <th>{{ 'label.homepage'|trans }}</th>
                        <td><a href="{{ customer.homepage }}" target="_blank">{{ customer.homepage|replace({'https://': '', 'http://': ''}) }}</a></td>
                    </tr>
                {% endif %}
                {% if customer.fax is not empty %}
                    <tr>
                        <th>{{ 'label.fax'|trans }}</th>
                        <td>{{ customer.fax }}</td>
                    </tr>
                {% endif %}
                {% if customer.timezone is not empty %}
                    <tr>
                        <th>{{ 'label.timezone'|trans }}</th>
                        <td><span data-toggle="tooltip" data-placement="top" title="{{ customer.timezone }}">{{ now|date_time }}</span></td>
                    </tr>
                {% endif %}
                {% if customer.currency is not empty %}
                    <tr>
                        <th>{{ 'label.currency'|trans }}</th>
                        <td>{{ customer.currency }}</td>
                    </tr>
                {% endif %}
                {% if is_granted('details', customer) %}
                    {% if customer.number is not empty %}
                        <tr>
                            <th>{{ 'label.number'|trans }}</th>
                            <td>{{ customer.number }}</td>
                        </tr>
                    {% endif %}
                    {% if customer.vatId is not empty %}
                        <tr>
                            <th>{{ 'label.vat_id'|trans }}</th>
                            <td>{{ customer.vatId }}</td>
                        </tr>
                    {% endif %}
                {% endif %}
                {% for metaField in customer.visibleMetaFields|sort((a, b) => a.order <=> b.order) %}
                    <tr>
                        <th>{{ metaField.label|trans }}</th>
                        <td>{{ widgets.form_type_value(metaField.type, metaField.value, customer) }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endblock %}
    {% endembed %}

    {{ render(controller('App\\Controller\\CustomerController::projectsAction', {'customer': customer.id, 'page': 1})) }}
    
    {% if stats is not null %}
        {{ include('customer/embed_budget.html.twig', {'customer': customer, 'stats': stats}) }}
    {% endif %}

    {% if can_edit %}
        {{ include('embeds/rates-table.html.twig', {'id': 'customer_rates_box', 'entity': customer, 'create_url': path('admin_customer_rate_add', {'id': customer.id}), 'delete_route': 'delete_customer_rate', 'currency': customer.currency}) }}
    {% endif %}

    {% if teams is not null %}
        {% set options = {'teams': teams, 'team': team} %}
        {% if is_granted('permissions', customer) %}
            {% set options = options|merge({'route_create': path('customer_team_create', {'id': customer.id}), 'route_edit': path('admin_customer_permissions', {'id': customer.id})}) %}
        {% endif %}
        {{ include('embeds/teams.html.twig', options) }}
    {% endif %}

    {% if comments is not null %}
        {% set options = {'form': commentForm, 'comments': comments} %}
        {% if can_edit %}
            {% set options = options|merge({'route_pin': 'customer_comment_pin', 'route_delete': 'customer_comment_delete'}) %}
        {% endif %}
        {{ include('embeds/comments.html.twig', options) }}
    {% endif %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        document.addEventListener('kimai.initialized', function() {
            KimaiReloadPageWidget.create('kimai.customerTeamUpdate kimai.customerUpdate kimai.teamUpdate kimai.projectTeamUpdate kimai.projectUpdate kimai.rateUpdate');
        });
    </script>
{% endblock %}

templates/customer/edit.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}
{% import "customer/actions.html.twig" as actions %}

{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}
{% block page_actions %}{{ actions.customer(customer, 'edit') }}{% endblock %}

{% block main %}
    {% set formEditTemplate = app.request.xmlHttpRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig' %}
    {% set formOptions = {
        'title': customer.name|default('create'|trans),
        'form': form,
        'back': path('admin_customer')
    } %}
    {% embed formEditTemplate with formOptions %}
        {% block form_body %}
            <div class="row">
                <div class="col-md-10">
                    {{ form_row(form.name) }}
                </div>
                <div class="col-md-2">
                    {{ form_row(form.color) }}
                </div>
            </div>
            {{ form_row(form.comment) }}
            {{ form_row(form.address) }}
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.company) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.number) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.vatId) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.country) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.currency) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.timezone) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.contact) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.email) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.homepage) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.mobile) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.phone) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.fax) }}
                </div>
            </div>
            {% if form.budget is defined %}
                <div class="row">
                    <div class="col-md-6">
                        {{ form_row(form.budget) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(form.timeBudget) }}
                    </div>
                </div>
            {% endif %}
            {{ form_row(form.visible) }}
            {% if form.metaFields is defined and form.metaFields is not empty %}
                {% for meta in form.metaFields|sort((a, b) => a.vars.data.order <=> b.vars.data.order) %}
                    {{ form_row(meta) }}
                {% endfor %}
            {% endif %}
            {{ form_widget(form) }}
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/customer/embed_budget.html.twig
{% embed '@AdminLTE/Widgets/box-widget.html.twig' with {'customer': customer, 'stats': stats} %}
    {% import "macros/progressbar.html.twig" as progress %}
    {% block box_title %}{{ 'label.budget'|trans }}{% endblock %}
    {% block box_attributes %}id="budget_box"{% endblock %}
    {% block box_body %}
        {% set currency = customer.currency %}

        {% set params = {
            '%activity%': '<strong>' ~ stats.activityAmount ~ '</strong>',
            '%project%': '<strong>' ~ stats.projectAmount ~ '</strong>',
            '%customer%': '<strong>' ~ customer.name ~ '</strong>',
            '%records%': '<strong>' ~ stats.recordAmount ~ '</strong>',
            '%duration%': '<strong>' ~ stats.recordDuration|duration ~ '</strong>',
            '%rate%': '<strong>' ~ stats.recordRate|money(currency) ~ '</strong>',
            '%internal_rate%': '<strong>' ~ stats.recordInternalRate|money(currency) ~ '</strong>'
        } %}

        <p>
            {{ 'admin_customer.short_stats'|trans(params)|raw }}
            {{ 'label.rate_internal'|trans }}: {{ stats.recordInternalRate|money(currency) }}.
        </p>

        {{ progress.progressbar(customer.budget, stats.recordRate, 'label.budget'|trans, stats.recordRate|money(currency) ~ ' / ' ~ customer.budget|money(currency) ) }}
        {{ progress.progressbar(customer.timeBudget, stats.recordDuration, 'label.timeBudget'|trans, stats.recordDuration|duration ~ ' / ' ~ customer.timeBudget|duration ) }}
    {% endblock %}
{% endembed %}

templates/customer/permissions.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}
{% import "customer/actions.html.twig" as actions %}

{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}
{% block page_actions %}{{ actions.customer(customer, 'permissions') }}{% endblock %}

{% block main %}
    {{ include(app.request.xmlHttpRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': customer.name,
        'form': form,
        'back': path('admin_customer')
    }) }}
{% endblock %}

templates/customer/rates.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}
{% import "customer/actions.html.twig" as actions %}

{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}
{% block page_actions %}{{ actions.customer(customer, 'rates') }}{% endblock %}

{% block main %}
    {{ include(app.request.xmlHttpRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': customer.name,
        'form': form,
        'back': path('admin_customer')
    }) }}
{% endblock %}